columns:
  age: int
  sex: category
  bmi: float
  children: int
  smoker: category
  region: category
  expenses: float

target_column: expenses

domain_values:
  sex:
    - female
    - male
  smoker:
    - yes
    - no
  region:
    - southwest
    - southeast
    - northwest
    - northeast


  